Peliculas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Peliculas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Peliculas/Controllers/PeliculaController.cs
using ML;
using Newtonsoft.Json;
using Peliculas;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Linq.Expressions;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
namespace Movies.Controllers
{
    public class PeliculaController : Controller
    {
        // GET: Peliculas
        
          
            public ActionResult GetAll()
            {
                ML.Pelis peliculas = new ML.Pelis();

                using (HttpClient client = new HttpClient())
                {
                    string URLMoviesPopular = ConfigurationManager.AppSettings["URLMoviesPopular"].ToString();
                    string TokenMoviesPopular = ConfigurationManager.AppSettings["TokenMoviesPopular"].ToString();

                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", TokenMoviesPopular);

                    client.BaseAddress = new Uri(URLMoviesPopular);
                   
                    var responseTask = client.GetAsync("movie/popular");

                    responseTask.Wait();

                    var result = responseTask.Result;

                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<ML.Pelis>();
                        readTask.Wait();

                        var peliculasList = readTask.Result;//API
                        peliculas = peliculasList;

                    }
                }

                return View(peliculas);
            }
          
        public ActionResult FavoritasGetAll()
        {
            ML.Pelis peliculafav = new ML.Pelis();

            try
            {
                using (HttpClient client = new HttpClient())
                {

                    string URLMoviesPopular = ConfigurationManager.AppSettings["URLMoviesPopular"].ToString();
                    string TokenMoviesPopular = ConfigurationManager.AppSettings["TokenMoviesPopular"].ToString();

                    client.BaseAddress = new Uri(URLMoviesPopular);
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", TokenMoviesPopular);
                  
                    var responseTask = client.GetAsync("account/21711153/favorite/movies");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode) {

                        var readTask = result.Content.ReadAsAsync<ML.Pelis>();
                        readTask.Wait();
                        peliculafav= readTask.Result;
                        TempData["Success"] = "Película agregada a favoritos.";
                    }
                    else
                    {
                        TempData["Error"] = "No se pudieron obtener las peliculas favoritas.";

                    }

                }
            }

            catch (Exception ex) {
                TempData["Error"] = $"Ocurrio un error:{ex.Message}";

            }
          return View(peliculafav);
        }


        public ActionResult AddFavoritas(int id)
        {
            ML.Pelis pelis = new ML.Pelis();
          

            try
            {
                using (HttpClient client = new HttpClient())
                {
                    string URLMoviesPopular = ConfigurationManager.AppSettings["URLMoviesPopular"].ToString();
                    string TokenMoviesPopular = ConfigurationManager.AppSettings["TokenMoviesPopular"].ToString();

                    client.BaseAddress = new Uri(URLMoviesPopular);
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", TokenMoviesPopular);

                   
                    var data = new
                    {
                        media_type = "movie",
                        media_id = id,
                        favorite = true
                    };

                    // Serializar el objeto a JSON
                    var jsonData = JsonConvert.SerializeObject(data);
                    var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                    // Hacer la solicitud POST
                    var responseTask = client.PostAsync("account/21711153/favorite", content);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["Success"] = "Película agregada a favoritos.";
                    }
                  
                    {
                        TempData["Error"] = "No se pudo agregar la película a favoritos.";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Ocurrió un error: {ex.Message}";
            }
            return RedirectToAction("FavoritasGetAll");


        }

    }


}

Peliculas/Controllers/UsuarioController.cs
using ML;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http.Headers;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Peliculas.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult GetAll()
        {
            ML.Users users = new ML.Users();
            using (HttpClient client = new HttpClient())
            {
                string URLUsuariosRandom = ConfigurationManager.AppSettings["URLUsuariosRandom"].ToString();
                
                client.BaseAddress = new Uri(URLUsuariosRandom);
                // HTTP GET
                var responseTask = client.GetAsync("");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Users>();
                    readTask.Wait();

                    users = readTask.Result;
                }
            }
            return View(users);
        }

        // Acción para obtener más usuarios (JSON)
        [HttpGet]
        public JsonResult GetMoreUsers()
        {
            ML.Users users = new ML.Users();
            using (HttpClient client = new HttpClient())
            {
                string URLUsuariosRandom = ConfigurationManager.AppSettings["URLUsuariosRandom"].ToString();

                client.BaseAddress = new Uri(URLUsuariosRandom);
                var responseTask = client.GetAsync("");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Users>();
                    readTask.Wait();
                    users = readTask.Result;
                }
            }
            return Json(users.results, JsonRequestBehavior.AllowGet);
        }
    }

}

Peliculas/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Peliculas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Peliculas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Peliculas/Views/Pelicula/FavoritasGetAll.cshtml
@model ML.Pelis

@{
    ViewBag.Title = "FavoritasGetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Favoritas</h2>
<div class="container">
    <div class="row">
        @foreach (ML.DatosPelicula datos in Model.results)
        {
            <div class="col-3">
                <div class="card">
                    <img class="card-img-top" src="http://image.tmdb.org/t/p/w1280/@datos.poster_path" alt="Card image cap" />
                    <div class="card-body">
                        <h5 class="card-title">@datos.original_title</h5>
                        <p class="card-text">@datos.overview</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Peliculas/Views/Pelicula/GetAll.cshtml
@model ML.Pelis

@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>GetAll</h2>
<div class="container">
    <div class="row">
       
            @foreach (ML.DatosPelicula datos in Model.results)
            {
                <div class="col-3">
                    <div class="card">
                        <img class="card-img-top" src="http://image.tmdb.org/t/p/w1280/@datos.poster_path" alt="Card image cap" />
                        <div class="card-body">
                            <h5 class="card-title">@datos.original_title</h5>
                            <p class="card-text">@datos.overview</p>
                            @Html.ActionLink("Agregar a Favoritos", "AddFavoritas", new { id = datos.id }, new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        
   
    </div>
</div>

Peliculas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>  
<head>
    <meta charset="utf-8" />         
         
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>
                        @Html.ActionLink("Movies", "GetAll", "Pelicula", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li>
                        @Html.ActionLink("Movies", "GetAll", "Usuario", new { area = "" }, new { @class = "nav-link" })
                    </li>


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Peliculas/Views/Usuario/GetAll.cshtml
@model ML.Users
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h1>RANDOM USER</h1>
    <p>Para agregar un nuevo usuario dar clic en el botón</p>
    <button id="CargarUsuario" class="btn btn-primary">Cargar Más Usuarios</button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Email</th>
            <th>Celular</th>
            <th>Edad</th>
            <th>Fecha de Nacimiento</th>
            <th>Foto</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.results != null)
        {
            foreach (var users in Model.results)
            {
                <tr>
                    <td>@users.name.first</td>
                    <td>@users.location.street.name, @users.location.city, @users.location.state, @users.location.country, @users.location.postcode</td>
                    <td>@users.email</td>
                    <td>@users.phone</td>
                    <td>@users.registered.age</td>
                    <td>@users.dob.date</td>
                    <td>
                        <img src="@users.picture.large" style="width:50px;height:50px;" />
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="7" class="text-center">No hay usuarios disponibles</td>
            </tr>
        }
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $("#CargarUsuario").on("click", function () {
            $.ajax({
                url: '@Url.Action("GetMoreUsers", "Usuario")',
                type: 'GET',
                success: function (data) {
                    if (data) {
                        data.forEach(user => {
                            let row = `<tr>
                                <td>${user.name.first}</td>
                                <td>${user.location.street.name}, ${user.location.city}, ${user.location.state}, ${user.location.country}, ${user.location.postcode}</td>
                                <td>${user.email}</td>
                                <td>${user.phone}</td>
                                <td>${user.registered.age}</td>
                                <td>${user.dob.date}</td>
                                <td><img src="${user.picture.large}" style="width:50px;height:50px;" /></td>
                            </tr>`;
                            $("table tbody").append(row);
                        });
                    } else {
                        alert("No se pudieron cargar más usuarios.");
                    }
                },
                error: function () {
                    alert("Error al cargar usuarios.");
                }
            });
        });
    });
</script>